### ISSUE TITLE
Feature: User can view an interactive map with markers of nearby boba shops.

### ISSUE THREAD

**Issue by jamessding** [jamessding/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view an interactive map with markers of nearby boba shops.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Once the user logs in, users can share their location and a map will show up populated with markers of nearby boba shops.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103629526/181349103-1193fd21-5195-4be6-9625-4c123fd4baa5.png)
![image](https://user-images.githubusercontent.com/103629526/181349256-6fe613dd-9e7d-4a59-87fb-9a543ee03b9b.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Implement Yelp API to get list of nearby boba shops based on current location.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Implement Geolocation API to get user's current latitude and longitude.
- [x] Create a component to render a map using googlemaps/react-wrapper, Maps JavaScript API, and current location.
- [x] Create a marker component to render a marker at a certain location.
- [x] Update map component to add markers to each nearby boba shop by passing them as a child component of the map.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
