### ISSUE TITLE
Feature: User can view an updated list of boba shops next to the map.

### ISSUE THREAD

**Issue by jamessding** [jamessding/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view an updated list of boba shops next to the map.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can view an updated list of boba shops based on where the map location moves.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-08-02 at 11 32 11 AM](https://user-images.githubusercontent.com/103629526/182448133-36b8a1ce-0534-4d17-953a-a2be84e1d8f1.png)
![Screen Shot 2022-08-02 at 11 32 30 AM](https://user-images.githubusercontent.com/103629526/182448144-79a344fc-6903-471b-b272-a3ed9e7ed794.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to get relevant information for each boba shop to turn into a card list.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a List component to render list of nearby boba shops fetched from Yelp API.
- [x] Update List component to show new list when user changes center location on map.
- [x] Update Map component to create a View List button, which will change view to list.
- [x] Update List component to create a View Map button, which will change view to map.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
