### ISSUE TITLE
Feature: User can view details after clicking on a specific boba shop.

### ISSUE THREAD

**Issue by jamessding** [jamessding/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view details after clicking on a specific boba shop.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can click on a specific boba shop to go to a new page filled with details of that boba shop.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-08-04 at 10 37 27 AM](https://user-images.githubusercontent.com/103629526/182915186-08c5518f-902b-45cd-ba6e-859787207a80.png)
![Screen Shot 2022-08-04 at 10 37 48 AM](https://user-images.githubusercontent.com/103629526/182915189-eedc980c-8561-4416-940e-eec979c7a2ac.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to implement Yelp API to get business id details.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a new page called details.jsx to render details of a specific boba shop by fetching from Yelp.
- [x] Implement hashrouting such that when user clicks on boba shop card, the new page's url will include a hashroute consisting of business id key and value.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
